name: Template
options:
  bundleIdPrefix: com.myapp
targets:
  Template:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [Template]
    settings:
      configs:
        debug:
          CUSTOM_BUILD_SETTING: my_debug_value
        release:
          CUSTOM_BUILD_SETTING: my_release_value
